"""
Generates the Veyl aperture mark.

The mark is an iris aperture: N congruent blades rotating into a hexagonal
opening. Privacy rendered as a mechanism rather than as a padlock.

Geometry is computed rather than hand-authored so the blades are provably
congruent and the rotational symmetry is exact. Re-run to regenerate:

    python scripts/build-logo.py

Construction
------------
Each blade k spans an angular sector on an outer circle of radius R, and is
closed by a straight "cutting edge" taken from a regular N-gon of circumradius
Ri that is rotated by BETA against the outer sectors. BETA is what turns a
plain segmented ring into an aperture: at 0 the blades read as a pie chart, at
half a sector they read as a shutter caught mid-close.
"""
from __future__ import annotations

import math
import pathlib

N = 6                    # blades
R = 25.0                 # outer radius
RI = 11.4                # inner polygon circumradius (the opening)
BETA = math.radians(30)  # blade rotation. half a sector = full aperture read
GAP = math.radians(3.2)  # kerf between blades
CX = CY = 32.0           # centre on a 64x64 canvas

OLIVE = "#4F5D31"
CANVAS = "#FAF9F5"

ROOT = pathlib.Path(__file__).resolve().parent.parent
BRAND = ROOT / "public" / "brand"


def pt(radius: float, angle: float) -> tuple[float, float]:
    """Polar to canvas coordinates. Y is flipped: SVG grows downward."""
    return (CX + radius * math.cos(angle), CY - radius * math.sin(angle))


def f(v: float) -> str:
    """Trim float noise so the path data stays readable and diffable."""
    return f"{v:.2f}".rstrip("0").rstrip(".")


def blade(k: int) -> str:
    sector = 2 * math.pi / N
    a0 = k * sector + GAP / 2
    a1 = (k + 1) * sector - GAP / 2

    # Outer arc endpoints.
    o0 = pt(R, a0)
    o1 = pt(R, a1)
    # Cutting edge: the inner polygon edge, rotated against the sector.
    i1 = pt(RI, a1 + BETA)
    i0 = pt(RI, a0 + BETA)

    # sweep-flag 0: SVG angles run clockwise once Y is flipped.
    return (
        f"M{f(o0[0])} {f(o0[1])}"
        f"A{f(R)} {f(R)} 0 0 0 {f(o1[0])} {f(o1[1])}"
        f"L{f(i1[0])} {f(i1[1])}"
        f"L{f(i0[0])} {f(i0[1])}"
        "Z"
    )


def blades() -> list[str]:
    return [blade(k) for k in range(N)]


def svg(body: str, extra: str = "") -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" '
        'width="64" height="64" role="img" aria-label="Veyl">\n'
        "  <title>Veyl</title>\n"
        f"{extra}{body}"
        "</svg>\n"
    )


def paths(fill: str, opacities: list[float]) -> str:
    out = []
    for k, d in enumerate(blades()):
        op = opacities[k]
        attr = f' opacity="{op}"' if op < 1 else ""
        out.append(f'    <path d="{d}" fill="{fill}"{attr}/>\n')
    return f'  <g>\n{"".join(out)}  </g>\n'


def main() -> None:
    BRAND.mkdir(parents=True, exist_ok=True)

    # Graduated opacity around the rotation: the aperture reads as *closing*,
    # not as a static rosette. Two blades sit back so the eye finds a start.
    grade = [1, 1, 0.86, 0.62, 0.44, 0.7]
    flat = [1] * N

    files = {
        # Tile: for favicons, avatars, anywhere needing its own ground.
        "veyl-mark.svg": svg(
            paths(CANVAS, grade),
            f'  <rect width="64" height="64" rx="14" fill="{OLIVE}"/>\n',
        ),
        # Glyph: transparent, olive. Nav lockup and light surfaces.
        "veyl-glyph.svg": svg(paths(OLIVE, grade)),
        # Mono: inherits currentColor. Print, stamps, single-colour contexts.
        "veyl-mark-mono.svg": svg(paths("currentColor", flat)),
    }

    for name, content in files.items():
        (BRAND / name).write_text(content, encoding="utf-8")
        print(f"  public/brand/{name}")

    # React component, emitted from the same geometry so the inline mark in
    # the nav can never drift from the asset files.
    rows = []
    for k, d in enumerate(blades()):
        op = "" if grade[k] == 1 else f' opacity="{grade[k]}"'
        rows.append(f'      <path d="{d}" fill="currentColor"{op} />')
    tsx_paths = "\n".join(rows)

    component = (
        "/* AUTO-GENERATED by scripts/build-logo.py. Do not edit.\n"
        "   Regenerate with: python scripts/build-logo.py */\n\n"
        "export function VeylMark({ className }: { className?: string }) {\n"
        "  return (\n"
        '    <svg viewBox="0 0 64 64" className={className} fill="none" aria-hidden>\n'
        f"{tsx_paths}\n"
        "    </svg>\n"
        "  )\n"
        "}\n"
    )
    comp_path = ROOT / "src" / "components" / "site" / "VeylMark.tsx"
    comp_path.write_text(component, encoding="utf-8")
    print("  src/components/site/VeylMark.tsx")

    # Favicon: flat opacity and a slightly wider opening. Graduated blades
    # turn to mush below ~20px, so the small size gets its own cut.
    global RI
    RI = 12.6
    (ROOT / "public" / "mark.svg").write_text(
        svg(paths(CANVAS, flat), f'  <rect width="64" height="64" rx="14" fill="{OLIVE}"/>\n'),
        encoding="utf-8",
    )
    print("  public/mark.svg")


if __name__ == "__main__":
    main()
